/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.backend.programming.learning.system.kafka.core.calendar.event.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum NotificationComponentType implements org.apache.avro.generic.GenericEnumSymbol<NotificationComponentType> {
  ASSIGNMENT, EXAM, POST, CONTEST, REMINDER  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"NotificationComponentType\",\"namespace\":\"com.backend.programming.learning.system.kafka.core.calendar.event.avro.model\",\"symbols\":[\"ASSIGNMENT\",\"EXAM\",\"POST\",\"CONTEST\",\"REMINDER\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
