/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.backend.programming.learning.system.kafka.core.calendar.event.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum UpdateState implements org.apache.avro.generic.GenericEnumSymbol<UpdateState> {
  CREATING, CREATED, UPDATING, UPDATED, DELETING, DELETED, DELETE_FAILED, UPDATE_FAILED, CREATE_FAILED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"UpdateState\",\"namespace\":\"com.backend.programming.learning.system.kafka.core.calendar.event.avro.model\",\"symbols\":[\"CREATING\",\"CREATED\",\"UPDATING\",\"UPDATED\",\"DELETING\",\"DELETED\",\"DELETE_FAILED\",\"UPDATE_FAILED\",\"CREATE_FAILED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
