/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.backend.programming.learning.system.kafka.code.assessment.code.question.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum CopyState implements org.apache.avro.generic.GenericEnumSymbol<CopyState> {
  CREATING, CREATED, UPDATING, UPDATED, DELETING, DELETED, DELETING_FAIL, UPDATING_FAIL, CREATING_FAIL  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"CopyState\",\"namespace\":\"com.backend.programming.learning.system.kafka.code.assessment.code.question.avro.model\",\"symbols\":[\"CREATING\",\"CREATED\",\"UPDATING\",\"UPDATED\",\"DELETING\",\"DELETED\",\"DELETING_FAIL\",\"UPDATING_FAIL\",\"CREATING_FAIL\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
